### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by AYadav01** [JenifferWuUCLA/pulmonary_nodules_AI_diagnosis#1]
Hi Jeniffer,

I am running the create_images.py files but I keep getting this error: 
IndexError: list index out of range

Also, how many subsets of Luna16 dataset are you using for creating test and train images.

Thank you

**Comment by JenifferWuUCLA** [comment]
Hi, 
    The the create_images.py file is out of date, and I have used all subsets of dataset. Especially, it is worth noting that the code of this project is for the "Tianchi lung cancer intelligent diagnosis" application.
